import argparse

def get_results():
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--fake_data', action='store_true', help="Use Fake Data generated by client", default=False)
    parser.add_argument('port', type=int, nargs=1)
    return parser.parse_args()